### ISSUE TITLE
Show cluster name too

### ISSUE THREAD

**Issue by vojbarzz** [hjacobs/kube-ops-view#171]
Would be nice to show cluster name defined at kubeconfig:

``` yaml
clusters:
- cluster:
    certificate-authority: certs/xxx.pem
    server: https://1.2.3.4:9999
  name: SomeFancyName
```

Current output: `https://1.2.3.4:9999`
Expected output: `SomeFancyName (https://1.2.3.4:9999)`
