### ISSUE TITLE
Clear screen

### ISSUE THREAD

**Issue by kolesoffac** [hjacobs/kube-ops-view#183]
I have deployed _kube-ops-view_.
But web ui is clear:
![image](https://user-images.githubusercontent.com/11459507/49282898-5a7f3c00-f4a1-11e8-8d14-a440f05fd108.png)

and logs:
```
10.244.0.1 - - [2018-11-30 10:07:01] "GET /events HTTP/1.1" 200 41692 24.337420
10.244.0.1 - - [2018-11-30 10:07:05] "GET /health HTTP/1.1" 200 117 0.000913
WARNING:kube_ops_view.kubernetes:Failed to query node metrics 10-96-0-1:443: 404 Not Found
WARNING:kube_ops_view.kubernetes:Failed to query pod metrics for cluster 10-96-0-1:443: 404 Not Found
10.244.0.1 - - [2018-11-30 10:07:06] "GET /health HTTP/1.1" 200 117 0.000713
WARNING:kube_ops_view.kubernetes:Failed to query node metrics 10-96-0-1:443: 404 Not Found
WARNING:kube_ops_view.kubernetes:Failed to query pod metrics for cluster 10-96-0-1:443: 404 Not Found
```

Can i fix it?

Thanks

**Comment by cristian04** [comment]
having the same issue using the latest version of the chart

**Comment by lgg42** [comment]
I have the same issue, with manifests and with helm, no information in logs like the OP.
Kubernetes 1.11 created with Kops.

**Comment by cristian04** [comment]
I found a workaround by adding more resources. I will send my values as soon as I can :)

**Comment by cristian04** [comment]
Please, try with this values

```
replicaCount: 3
resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 256Mi```

**Comment by lgg42** [comment]
Thanks for your comments! I just tried it out with your values, and it didn't work. For some reason I wanted to try deploying it in *default* namespace (I was using another) and it DID work.

So my problem was: deploying it in a namespace different than *default*
Could you try the default values but in the default namespace? or were you deploying it in default namespace already?

**Comment by netflash** [comment]
Same for me... it works fine yesterday, but now it's clear screen.
I tried to set 256Mi, then 512Mi - same story :-(

**Comment by cristian04** [comment]
I started having issues now as well. It was running on another namespace (not default) but now is down.

**Comment by cristian04** [comment]
This is working after the following changes:

1- Debug mode:
I've added a debug flag to get additional info:
Add this to your values.yaml

```
debug: true
```
and this to your deployment template:

```
{{- if.Values.debug}}
        args:
        - --debug
        {{- end}}
```
2- Change readiness and liveness times.
```
livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 15
          timeoutSeconds: 5
```
I will send a PR soon :)
